default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
modern-dark: styles/modern-dark.scss
modern-contrast: styles/modern-contrast.scss
modern-light: styles/modern-light.scss
